### ISSUE TITLE
What is a case opening system?

### ISSUE THREAD

**Issue by remram44** [mberkdemir/godot-casesimulator#1]
I got here from [This Week In Godot](https://thisweekingodot.com/posts/issue-31) and I'm a bit confused. Do you per chance mean [loot boxes](https://en.wikipedia.org/wiki/Loot_box) or crates?

You might want to clarify this a little, the term is probably unfamiliar to more people than just me :wink:

**Comment by mberkdemir** [comment]
Hello, here is the [video](https://www.youtube.com/watch?v=u_A22VfpG1k) about how it looks like. I have made some research and on social media like youtube most people name the content "case opening in CS:GO". So, I thought that it could be good if I name the project "case opening system" or "case simulator".
